steps:
  - name: 'gcr.io/cloud-builders/docker'
      args: ['build', '-t', 'us-east1-docker.pkg.dev/cloudside-academy/test-demo/test-app', '.']

  - name: 'gcr.io/cloud-builders/docker'
      args: ['push', 'us-east1-docker.pkg.dev/cloudside-academy/test-demo/test-app']
